platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 6.3.1

inputs:
- name: osusume-js

run:
  path: ./osusume-js/ci/test.sh

outputs:
- name: built-osusume-js
  path: ./osusume-js/dist