export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';
export const SELECT_SUGGESTION = 'SELECT_SUGGESTION';
export const FETCH_CUISINE_TYPES_SUCCESS = 'FETCH_CUISINE_TYPES_SUCCESS';
