export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';
export const FETCH_CUISINE_TYPES_SUCCESS = 'FETCH_CUISINE_TYPES_SUCCESS';
export const FETCH_PRICE_RANGES_SUCCESS = 'FETCH_PRICE_RANGES_SUCCESS';
export const CREATE_RESTAURANT_SUCCESS = 'CREATE_RESTAURANT_SUCCESS';
